### Dictionary

In [3]:
dict_1 = {'Name': 'Nirav', "Hobbies":["Coding", "Gamer", "Music"], 24:2004}
dict_1

{'Name': 'Nirav', 'Hobbies': ['Coding', 'Gamer', 'Music'], 24: 2004}

In [4]:
dict_1.keys()

dict_keys(['Name', 'Hobbies', 24])

In [5]:
dict_1.values()

dict_values(['Nirav', ['Coding', 'Gamer', 'Music'], 2004])

In [6]:
dict_1['Name']="Changela"
dict_1

{'Name': 'Changela', 'Hobbies': ['Coding', 'Gamer', 'Music'], 24: 2004}

In [7]:
del dict_1['name']

KeyError: 'name'

In [8]:
dict_1

{'Name': 'Changela', 'Hobbies': ['Coding', 'Gamer', 'Music'], 24: 2004}

### Sets

In [9]:
ex_set={1,2,3,4,5,1,13.4,9.6,"hi",-1,11.4,"hello",21.5,"ds"}
ex_set

{-1, 1, 11.4, 13.4, 2, 21.5, 3, 4, 5, 9.6, 'ds', 'hello', 'hi'}

In [10]:
ex_set[0]

TypeError: 'set' object is not subscriptable

In [11]:
ex_set.add(100)
ex_set
ex_set.remove(-1)
ex_set

{1, 100, 11.4, 13.4, 2, 21.5, 3, 4, 5, 9.6, 'ds', 'hello', 'hi'}

## Numpy

In [12]:
import numpy as np

In [13]:
sim_list=[6,7,9]
np.array(sim_list)

array([6, 7, 9])

In [14]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [15]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.arange(1,36,5) #shift + tab

array([ 1,  6, 11, 16, 21, 26, 31])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
np.ones((2,3)) #(row,column)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [31]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [32]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [33]:
np.random.rand(3,5)

array([[0.64626297, 0.06056267, 0.25804885, 0.74023003, 0.59510922],
       [0.12648643, 0.73318675, 0.85449702, 0.93338421, 0.69046139],
       [0.69114821, 0.59242221, 0.47105216, 0.096868  , 0.56652173]])

In [34]:
#"randn" negative value
arr=np.random.randn(2,4)
arr

array([[ 0.91781371,  1.40472973,  0.364437  ,  1.57936053],
       [-0.66512523, -0.73915339,  0.73654443,  0.07373173]])

In [35]:
np.random.randint(2,100)

23

In [36]:
np.random.randint(2,56,100)

array([19, 25, 52, 40, 23, 49, 12, 23, 36, 37, 33,  6, 33,  3, 18, 53, 46,
       50,  6, 23,  6, 34,  9, 39,  9, 37, 43,  6, 30, 55,  6, 19, 31, 22,
       24, 30, 13, 16, 46, 35, 36,  9, 25, 38, 53,  7, 44, 46, 28, 47, 49,
       12, 27, 45, 50, 48, 45, 51, 53, 15, 44, 14,  9, 13, 43, 14, 31, 47,
       34,  8, 12, 33, 43,  9, 33, 39, 18, 51,  5, 37, 49, 46,  2, 25, 28,
       30,  4, 54,  9, 37, 17, 27, 16,  4, 31, 26,  6,  7, 37, 51])

In [37]:
sam_array=np.arange(30)
sam_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
rand_array=np.random.randint(0,10,50)
rand_array

array([5, 2, 5, 3, 7, 8, 7, 7, 8, 0, 9, 1, 8, 0, 7, 0, 9, 2, 9, 7, 2, 3,
       9, 5, 0, 3, 2, 3, 8, 4, 3, 9, 4, 2, 4, 1, 4, 8, 7, 1, 4, 2, 9, 6,
       7, 9, 7, 6, 4, 3])

In [39]:
sam_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
sam_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [42]:
rand_array.max()

9

In [44]:
rand_array.argmax()

10

In [45]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
sam_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sam_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [59]:
sam_matrix[1,2]

21

In [60]:
sam_matrix[2,:]

array([56, 76, 24,  7])

In [61]:
sam_matrix[2]

array([56, 76, 24,  7])

In [62]:
sam_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

### Selection Technique

In [65]:
sam_array =np.arange(1,20)
sam_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [66]:
sam_array+sam_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [67]:
np.exp(sam_array)#exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [68]:
np.sqrt(sam_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [69]:
np.log(sam_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [70]:
np.max(sam_array)

19

In [71]:
np.min(sam_array)

1

In [73]:
np.argmax(sam_array)

18

In [74]:
np.argmin(sam_array)

0

In [75]:
np.square(sam_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [76]:
 np.std(sam_array)

5.477225575051661

In [77]:
np.var(sam_array)

30.0

In [78]:
np.mean(sam_array)

10.0

In [82]:
array=np.random.randn(3,4)

In [85]:
np.round(array,decimals =2)

array([[ 0.55,  0.22,  0.45,  0.76],
       [ 0.52, -1.62,  0.71, -0.12],
       [ 1.46, -0.04,  1.05,  1.24]])

In [86]:
sports= np.array(['golf','cricket','fball','bball'])
np.unique(sports)

array(['bball', 'cricket', 'fball', 'golf'], dtype='<U7')

 ### pandas

In [88]:
import pandas as pd
import numpy as np

### Dataframe and indexing

In [89]:
sports1=pd.Series([1,2,3,4], index= ['golf','cricket','fball','bball']) #series single data
sports1

golf       1
cricket    2
fball      3
bball      4
dtype: int64

In [90]:
sports1['fball']

3

In [91]:
sports2=pd.Series([11,2,3,4], index= ['golf','cricket','fball','baseball'])
sports2

golf        11
cricket      2
fball        3
baseball     4
dtype: int64

In [92]:
sports1+sports2

baseball     NaN
bball        NaN
cricket      4.0
fball        6.0
golf        12.0
dtype: float64

In [94]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(), columns= 'S1 S2 S3 S4 S5'.split())
df1

S1        S2        S3        S4        S5
A  0.294394  0.774065  0.521943  0.612983  0.759245
B  0.467123  0.740793  0.041445  0.947799  0.862503
C  0.323018  0.455758  0.024166  0.530705  0.384826
D  0.478540  0.400996  0.990621  0.703088  0.878957
E  0.182240  0.076558  0.556663  0.312766  0.822548
F  0.400358  0.048095  0.853373  0.690855  0.731527
G  0.066617  0.120237  0.886077  0.271750  0.260802
H  0.296863  0.962032  0.999209  0.548335  0.309731

In [95]:
df1['S1']

A    0.294394
B    0.467123
C    0.323018
D    0.478540
E    0.182240
F    0.400358
G    0.066617
H    0.296863
Name: S1, dtype: float64

In [99]:
df1[['S1','S2']]

S1        S2
A  0.294394  0.774065
B  0.467123  0.740793
C  0.323018  0.455758
D  0.478540  0.400996
E  0.182240  0.076558
F  0.400358  0.048095
G  0.066617  0.120237
H  0.296863  0.962032

In [100]:
df1['S6']= df1['S1']+ df1['S2']
df1

S1        S2        S3        S4        S5        S6
A  0.294394  0.774065  0.521943  0.612983  0.759245  1.068460
B  0.467123  0.740793  0.041445  0.947799  0.862503  1.207915
C  0.323018  0.455758  0.024166  0.530705  0.384826  0.778776
D  0.478540  0.400996  0.990621  0.703088  0.878957  0.879536
E  0.182240  0.076558  0.556663  0.312766  0.822548  0.258797
F  0.400358  0.048095  0.853373  0.690855  0.731527  0.448453
G  0.066617  0.120237  0.886077  0.271750  0.260802  0.186854
H  0.296863  0.962032  0.999209  0.548335  0.309731  1.258895

In [102]:
df2={'ID':['101','102','103','107','176'], 'Name':['Nirav','Udit','Jash','Vishal','Manav'], 'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID    Name  Profit
0  101   Nirav      20
1  102    Udit      54
2  103    Jash      56
3  107  Vishal      87
4  176   Manav     123

In [103]:
df['ID']

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [104]:
df[['ID','Name']]

ID    Name
0  101   Nirav
1  102    Udit
2  103    Jash
3  107  Vishal
4  176   Manav

In [108]:
df=df.drop('ID',axis=1)
df

Name  Profit
0   Nirav      20
1    Udit      54
2    Jash      56
3  Vishal      87
4   Manav     123

In [109]:
df

Name  Profit
0   Nirav      20
1    Udit      54
2    Jash      56
3  Vishal      87
4   Manav     123

In [110]:
df.drop(3)

Name  Profit
0  Nirav      20
1   Udit      54
2   Jash      56
4  Manav     123