### Dictionary

In [2]:
dict_1 = {'Name': 'Nirav', "Hobbies":["Coding", "Gamer", "Music"], 24:2004}
dict_1

{'Name': 'Nirav', 'Hobbies': ['Coding', 'Gamer', 'Music'], 24: 2004}

In [3]:
dict_1.keys()

dict_keys(['Name', 'Hobbies', 24])

In [4]:
dict_1.values()

dict_values(['Nirav', ['Coding', 'Gamer', 'Music'], 2004])

In [6]:
dict_1['Name']="Changela"
dict_1

{'Name': 'Changela',
 'Hobbies': ['Coding', 'Gamer', 'Music'],
 24: 2004,
 'name': 'Changela'}

In [7]:
del dict_1['name']

In [8]:
dict_1

{'Name': 'Changela', 'Hobbies': ['Coding', 'Gamer', 'Music'], 24: 2004}

### Sets

In [10]:
ex_set={1,2,3,4,5,1,13.4,9.6,"hi",-1,11.4,"hello",21.5,"ds"}
ex_set

{-1, 1, 11.4, 13.4, 2, 21.5, 3, 4, 5, 9.6, 'ds', 'hello', 'hi'}

In [11]:
ex_set[0]

TypeError: 'set' object is not subscriptable

In [12]:
ex_set.add(100)
ex_set
ex_set.remove(-1)
ex_set

{1, 100, 11.4, 13.4, 2, 21.5, 3, 4, 5, 9.6, 'ds', 'hello', 'hi'}

## Numpy

In [13]:
import numpy as np

In [14]:
sim_list=[6,7,9]
np.array(sim_list)

array([6, 7, 9])

In [15]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [16]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
np.arange(1,36,5) #shift + tab

array([ 1,  6, 11, 16, 21, 26, 31])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.ones((2,3)) #(row,column)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [31]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [32]:
np.random.rand(3,5)

array([[0.21412699, 0.38508706, 0.01511753, 0.16252537, 0.63535911],
       [0.08780111, 0.39826917, 0.09364987, 0.02980956, 0.75102773],
       [0.96244821, 0.66197918, 0.50114601, 0.04357974, 0.86926279]])

In [39]:
#"randn" negative value
arr=np.random.randn(2,4)
arr

array([[-0.74104711, -0.0333466 , -0.10462607, -1.11629286],
       [ 1.37854316,  0.16525698, -0.03448728,  1.11799765]])

In [41]:
np.random.randint(2,100)

13

In [42]:
np.random.randint(2,56,100)

array([10, 11, 32,  7, 49, 27, 18,  2, 54, 13, 35, 48,  5, 33, 19, 39, 22,
       50, 35, 22,  4, 24, 28, 46, 19, 47, 26, 42, 29, 15,  4, 42, 32, 45,
       30, 42, 53, 12, 53, 44, 21, 37, 28, 43, 51, 15, 52, 40, 53,  4, 36,
       48, 10, 20, 50, 30,  5, 50, 42, 11, 25, 14, 46, 20, 33, 21, 19,  9,
       38, 19, 21, 26, 54, 15, 11, 19, 54, 31, 54,  2, 41,  7, 54, 48, 13,
       12,  7, 47, 55, 24, 24, 52,  4, 40, 49, 10, 44, 35, 12, 44])

In [43]:
sam_array=np.arange(30)
sam_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
rand_array=np.random.randint(0,10,50)
rand_array

array([9, 4, 8, 6, 7, 5, 7, 1, 8, 8, 5, 0, 7, 4, 2, 1, 4, 2, 4, 2, 4, 7,
       7, 4, 9, 9, 8, 9, 4, 5, 6, 3, 6, 2, 3, 7, 5, 5, 1, 2, 0, 0, 6, 0,
       5, 4, 5, 6, 5, 7])

In [50]:
sam_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
sam_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)